-- Schéma ukázkové e-shopové databáze pro n8n agenta (úkol 2).
-- Postgres / Supabase. Cíleně malé, ale s vazbami, aby šlo demonstrovat
-- JOINy a agregace. Vše ve schématu `public`.

DROP TABLE IF EXISTS tikety CASCADE;
DROP TABLE IF EXISTS polozky_objednavky CASCADE;
DROP TABLE IF EXISTS objednavky CASCADE;
DROP TABLE IF EXISTS produkty CASCADE;
DROP TABLE IF EXISTS kategorie CASCADE;
DROP TABLE IF EXISTS zakaznici CASCADE;

CREATE TABLE kategorie (
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazev  text NOT NULL UNIQUE,
    popis  text
);

CREATE TABLE zakaznici (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmeno       text NOT NULL,
    prijmeni    text NOT NULL,
    email       text NOT NULL UNIQUE,
    mesto       text,
    zeme        text NOT NULL DEFAULT 'CZ',
    registrace  date NOT NULL,
    vip         boolean NOT NULL DEFAULT false
);

CREATE TABLE produkty (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazev         text NOT NULL,
    kategorie_id  integer NOT NULL REFERENCES kategorie(id),
    znacka        text,
    cena_kc       numeric(10,2) NOT NULL,
    skladem       integer NOT NULL DEFAULT 0,
    hodnoceni     numeric(2,1),                   -- 1.0 - 5.0
    aktivni       boolean NOT NULL DEFAULT true
);

CREATE TABLE objednavky (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zakaznik_id    integer NOT NULL REFERENCES zakaznici(id),
    datum          date NOT NULL,
    stav           text NOT NULL,   -- nova / zaplacena / odeslana / dorucena / stornovana
    zpusob_platby  text NOT NULL,   -- karta / prevod / dobirka
    doprava_kc     numeric(10,2) NOT NULL DEFAULT 0,
    celkem_kc      numeric(10,2) NOT NULL   -- položky + doprava
);

CREATE TABLE polozky_objednavky (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objednavka_id  integer NOT NULL REFERENCES objednavky(id),
    produkt_id     integer NOT NULL REFERENCES produkty(id),
    mnozstvi       integer NOT NULL,
    cena_ks_kc     numeric(10,2) NOT NULL   -- cena za kus v době objednávky
);

-- Jediná tabulka, do které agent zapisuje (nástroj `zaloz_tiket`).
CREATE TABLE tikety (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zakaznik_id  integer REFERENCES zakaznici(id),
    predmet      text NOT NULL,
    popis        text NOT NULL,
    priorita     text NOT NULL DEFAULT 'normalni',  -- nizka / normalni / vysoka
    stav         text NOT NULL DEFAULT 'otevreny',
    vytvoreno    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_produkty_kategorie ON produkty(kategorie_id);
CREATE INDEX idx_objednavky_zakaznik ON objednavky(zakaznik_id);
CREATE INDEX idx_objednavky_datum ON objednavky(datum);
CREATE INDEX idx_polozky_objednavka ON polozky_objednavky(objednavka_id);
CREATE INDEX idx_polozky_produkt ON polozky_objednavky(produkt_id);

-- Supabase má na tabulkách ve `public` zapnuté RLS varování; agent se ale
-- připojuje přímo přes Postgres (role postgres), ne přes PostgREST/anon klíč,
-- takže RLS jeho dotazy neovlivňuje. Data jsou ukázková, ne osobní.
